### ISSUE TITLE
Feature parity with ReactJS.Net

### ISSUE THREAD

**Issue by xtroncode** [DaniilSokolyuk/ZeroReact.NET#6]
Hi, Will this project be updated to achieve feature parity with ReactJS.Net or will the optimisations made here be ported to ReactJS.Net ?

Thankyou.

**Comment by DaniilSokolyuk** [comment]
I have another similar project, https://github.com/DaniilSokolyuk/NodeReact.NET, we are currently using it in production. What features do you need?

**Comment by xtroncode** [comment]
Hi, We use render-functions for libs like React-Helmet and loadable components. Also does NodeReact.NET support running on linux ?

**Comment by DaniilSokolyuk** [comment]
NodeReact.NET based on [Javascript.NodeJS](https://github.com/JeringTech/Javascript.NodeJS) and supports linux, and some features like debug SSR code via Chrome. Also in linux NodeJS slightly faster than in Windows. Render functions is not yet available, but you can create feature request issue, it's not trivial but possible
